spring:
  datasource:
    url: jdbc:h2:mem:hw06-jpa;MODE=PostgreSQL
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: true
  shell:
    interactive:
      enabled: true
    script:
      enabled: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
  sql:
    init:
      mode: never
logging:
  level:
    org:
      springframework.orm.jpa: error
    root: error
