spring:
  messages:
    encoding: UTF-8
  data:
    rest:
      base-path: /datarest
  datasource:
    url: jdbc:h2:mem:hw13
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: true
  shell:
    interactive:
      enabled: true
    script:
      enabled: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
  sql:
    init:
      mode: never
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jmx:
    enabled: true
management:
  endpoints:
    access:
      default: read_only
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      access: read_only
    health:
      show-details: always
  health:
    defaults:
      enabled: true
logging:
  file:
    name: ./logs/spring-boot-logger.log
  config: classpath:logback.xml