CREATE TABLE IF NOT EXISTS etldataprocessor.processed_file_history
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    correlation_id     VARCHAR(39)                             NOT NULL,
    created_at         TIMESTAMP with time zone                NOT NULL,
    updated_at         TIMESTAMP with time zone                NOT NULL,
    version            BIGINT,
    file_name          VARCHAR(500)                            NOT NULL,
    file_path          VARCHAR(1000)                           NOT NULL,
    file_hash          VARCHAR(64)                             NOT NULL,
    file_size          BIGINT,
    company            VARCHAR(100)                            NOT NULL,
    processed_at       TIMESTAMP with time zone                NOT NULL,
    status             VARCHAR(20)                             NOT NULL,
    records_processed  INTEGER,
    records_failed     INTEGER,
    error_message      VARCHAR(2000),
    batch_id           UUID,
    processing_time_ms BIGINT,
    s3_etag            VARCHAR(100),
    CONSTRAINT pk_processed_file_history PRIMARY KEY (id)
);

ALTER TABLE etldataprocessor.processed_file_history ADD CONSTRAINT UC_PROCESSED_FILE_HISTORY_CORRELATION UNIQUE (correlation_id);

ALTER TABLE etldataprocessor.processed_file_history ADD CONSTRAINT uk_file_processing UNIQUE (file_path, file_hash);

CREATE INDEX idx_company_status ON etldataprocessor.processed_file_history (company, status);

CREATE INDEX idx_file_path_hash ON etldataprocessor.processed_file_history (file_path, file_hash);

CREATE INDEX idx_processed_at ON etldataprocessor.processed_file_history (processed_at);